'use client';
import {useCallback, useEffect, useRef, useState} from 'react';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {getJson, PondListResponse, PondSummary} from '../api';

type State='loading'|'ok'|'zero'|'network_error'|'http_error'|'invalid_json'|'timeout';
export function PondMap({initialItems=[]}:{initialItems?:PondSummary[]}){
 const mapRef=useRef<maplibregl.Map|null>(null); const divRef=useRef<HTMLDivElement|null>(null); const abortRef=useRef<AbortController|null>(null); const [items,setItems]=useState(initialItems); const [missing,setMissing]=useState(0); const [state,setState]=useState<State>('loading'); const [error,setError]=useState('');
 const toGeoJson=(ponds:PondSummary[])=>({type:'FeatureCollection' as const,features:ponds.filter(p=>p.location).map(p=>({type:'Feature' as const,geometry:p.location!,properties:{id:p.pondId,name:p.name,risk:p.risk?.riskLevel||'未評価',quality:p.coordinateQuality,flags:JSON.stringify(p.qualityFlags)}}))});
 const load=useCallback(async (bbox?:string)=>{abortRef.current?.abort(); const ctrl=new AbortController(); abortRef.current=ctrl; setState('loading'); try{const data=await getJson<PondListResponse>(`/ponds?limit=5000${bbox?`&bbox=${bbox}`:''}`,{signal:ctrl.signal,timeoutMs:10000}); setItems(data.items); setMissing(data.items.filter(p=>!p.location).length); setState(data.items.length?'ok':'zero'); const src=mapRef.current?.getSource('ponds') as maplibregl.GeoJSONSource|undefined; src?.setData(toGeoJson(data.items));}catch(e:any){if(ctrl.signal.aborted) return; setError(e?.message||String(e)); setState(e?.kind==='invalid_json'?'invalid_json':e?.kind==='timeout'?'timeout':e?.status?'http_error':'network_error');}},[]);
 useEffect(()=>{if(!divRef.current||mapRef.current) return; const map=new maplibregl.Map({container:divRef.current,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[138,36],zoom:4}); mapRef.current=map; map.addControl(new maplibregl.NavigationControl()); map.on('error',ev=>{console.warn('MapLibre tile/style error', ev.error)}); map.on('load',()=>{map.addSource('ponds',{type:'geojson',data:toGeoJson(items),cluster:true,clusterRadius:50}); map.addLayer({id:'clusters',type:'circle',source:'ponds',filter:['has','point_count'],paint:{'circle-color':'#2563eb','circle-radius':['step',['get','point_count'],16,100,22,1000,30]}}); map.addLayer({id:'cluster-count',type:'symbol',source:'ponds',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':12}}); map.addLayer({id:'pond-points',type:'circle',source:'ponds',filter:['!',['has','point_count']],paint:{'circle-color':['match',['get','risk'],'high','#dc2626','medium','#f59e0b','low','#16a34a','#64748b'],'circle-radius':7,'circle-stroke-width':1,'circle-stroke-color':'#fff'}}); map.on('click','pond-points',e=>{const f=e.features?.[0]; if(!f) return; const c=(f.geometry as any).coordinates; new maplibregl.Popup().setLngLat(c).setHTML(`<b>${f.properties?.name}</b><br/>リスク:${f.properties?.risk}<br/>品質:${f.properties?.quality}<br/><a href="/ponds/${f.properties?.id}">詳細</a>`).addTo(map);}); load();}); let timer:any; map.on('moveend',()=>{clearTimeout(timer); timer=setTimeout(()=>{const b=map.getBounds(); load(`${b.getWest()},${b.getSouth()},${b.getEast()},${b.getNorth()}`);},350);}); return()=>{abortRef.current?.abort(); map.remove(); mapRef.current=null};},[load]);
 return <section><div className="mapLibre" data-testid="maplibre-map" ref={divRef}/><p><span className="pill">状態 {state}</span><span className="pill">表示 {items.filter(p=>p.location).length}件</span><span className="pill">座標欠損 {missing}件</span></p>{state!=='ok'&&state!=='loading'&&<div className="warn">{state}: {error}<button onClick={()=>load()}>再試行</button></div>}</section>;
}
